# Generated by Django 5.2.4 on 2025-07-20 04:52

import ckeditor.fields
import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
        migrations.RenameField(
            model_name='email',
            old_name='title',
            new_name='عنوان',
        ),
        migrations.RemoveField(
            model_name='email',
            name='body',
        ),
        migrations.RemoveField(
            model_name='email',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='email',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='email',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='email',
            name='اسلاگ',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='email',
            name='تاریخ_ایجاد',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 20, 4, 51, 9, 127902, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='تاریخ_بروزرسانی',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='email',
            name='متن',
            field=ckeditor.fields.RichTextField(default='متن پیش\u200cفرض', verbose_name='متن'),
            preserve_default=False,
        ),
    ]
