# Generated by Django 5.2.4 on 2025-07-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_smsverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
