# Generated by Django 5.2.4 on 2025-07-19 18:03

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logintoken',
            options={'verbose_name': 'توکن ورود', 'verbose_name_plural': 'توکن\u200cهای ورود'},
        ),
        migrations.AlterModelOptions(
            name='smsverificationcode',
            options={'verbose_name': 'کد تأیید پیامکی', 'verbose_name_plural': 'کدهای تأیید پیامکی'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='logintoken',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='smsverificationcode',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default='2025-07-19', verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده'),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='token',
            field=models.CharField(max_length=50, unique=True, verbose_name='توکن'),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='code',
            field=models.CharField(max_length=10, verbose_name='کد تایید'),
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='smsverificationcode',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=8, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='users',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='نام کاربری'),
        ),
    ]
